### ISSUE TITLE
Post cache ignored on next run

### ISSUE THREAD

**Issue by DylanVanAssche** [klausi/mastodon-twitter-sync#25]
# Description

I have an existing Mastodon and Twitter account with several Tweets and Toots.
I used the flag `--skip-existing-posts` to avoid posting existing posts. This works fine, the posts are added to the post_cache.json file.
However on the next run, I removed the `--skip-existing-posts` flag to post the new Tweets and Toots on these accounts, but the post cache is ignored. Fortunately, I used `--dry-run` to see first what was going to be posted on Twitter and Mastodon.

# Steps to reproduce

1. Build it: `cargo build`. Adding `--release` on ARM seems to fail because of optimizations.
2. Run it with skipping posts flag: `cargo run -- --skip-existing-posts`
3. Run it normally: `cargo run -- --dry-run`
4. Existing posts, added to the cache, are shown again in step 3.

# Environment
- Rust 1.43.0
- Ubuntu 18.04 LTS
- armv7hl
- Master branch of `mastodon-twitter-sync`

**Comment by klausi** [comment]
Thanks a lot for testing! I think this might be related to a recent refactoring of the post cache. I think we should refactor the code to also have test coverage for the dry run and skip existing posts option, I will look into that!

**Comment by klausi** [comment]
Just tested this and I think this works as intended. `--dry-run` means nothing will be added to the post cache because on a dry run nothing is posted. So the option `--skip-existing-posts` does not actually mark the posts to be skipped because this is a dry run.

The correct execution would be: `cargo run -- --skip-existing-posts` (without dry run), then that is persisted to the post cache. I will put that example in the README.

**Comment by klausi** [comment]
For the failing release build on ARM: can you remove the profile.release section in Cargo.toml and try again? Maybe the lto option does not work on ARM.

**Comment by DylanVanAssche** [comment]
Thanks for such a great sync bridge :) 
Oh I made a typo in my issue description (edited it now). I didn't run `skip-existing-posts` with the `dry-run` flag. The cache is filled, but If you run again, the sync bridge wants to post the Tweets and Toots from the cache again.

1. `rm post_cache.json`: clean
2. `cargo run --release -- --skip-existing-posts`: fill cache with existing posts
3. `cat post_cache.json`: A lot of entries, so the cache is filled
4. `cargo run --release -- --dry-run`: posts in cache are shown in the output for posting.

**Example**:

`post_cache.json`
```
mastodon@matrix:~/mastodon-twitter-sync$ cat post_cache.json | grep "GPS location"
  "GPS location and satellite positions on @JollaHQ  #SailfishOS with gpsd on the @thepine64 PinePhone! #linux #mainline",
```
`cargo run --release -- --dry-run`
```
...
Posting to Twitter: GPS location and satellite positions on @JollaHQ  #SailfishOS with gpsd on the @thepine64 PinePhone! #linux #mainline 
```

**Comment by klausi** [comment]
I see, maybe the size of the post cache was not big enough (50). If we get 50 tweets and 50 toots then the cache size must be at least 100. I set it to 150 now, just to be sure in aad7fedb3633cb01cdb6447f88a4c104e92f4a7b .

But that does not explain your problem where you explicitly have the same text in the post cache, so the output should actually be `Error: preventing double posting to Mastodon: GPS location and satellite positions ...`. Which is not a super good error message because in this case skipping existing posts is intentional.

Quickly tried to reproduce on my accounts, but did not happen there. Do you only see this one post in the output or all of them? Maybe the cache file could not be read for some reason and it falls back to an empty cache silently?

**Comment by DylanVanAssche** [comment]
Indeed! The cache was returned empty... Raising the limit fixed it!

Note: The ARM build was fixed with the removal of `lto` in the `Cargo.toml` file.

**Comment by bajtos** [comment]
> Note: The ARM build was fixed with the removal of `lto` in the `Cargo.toml` file.

Interesting! The `lto` flag was added by me. I am building for ARM too and would like to have a smaller executable. What build-chain do you use for your ARM builds? I am using https://github.com/messense/rust-musl-cross and running the build inside a Docker image.

**Comment by DylanVanAssche** [comment]
I use the default Ubuntu build-chain `aarch64`. I compile on device.
