### ISSUE TITLE
Twitter access token generated lacks write permission

### ISSUE THREAD

**Issue by ln5** [klausi/mastodon-twitter-sync#3]
As mentioned in #2:

> Re the permission, my application has read and write but my access_token has read-only. I can indeed change permissions for the app, but not for the token. I suspect that I could work around this by generating a new token from the web page and edit the mastodon-twitter-sync.toml file. I'd rather follow your instructions though.

An access token apparently has an "Access Level" which AFAICT can be "Read" or "Read and write", possibly more. The access token created by mastodon-twitter-sync has "Read" and can not be changed at https://apps.twitter.com/app/<APPID>/keys.

I've confirmed that mastodon-twitter-sync works as expected w.r.t. posting to Twitter if an access token is created manually, at the apps.twitter.com page.

**Comment by klausi** [comment]
Sorry for the late reply.

Just tested the Twitter App creation process again and the access token was created correctly with "Read and Write" access. The developer agreement and all the forms to fill out is really annoying, but otherwise the Twitter defaults look correct and there is also no permission setting we could supply client-side. So if your app has "Read and Write" access then the access token will also get created with "Read and Write" access.

Let me know if this is still a problem.
